version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_secure_coding
    volumes:
      - .:/var/www/html
    ports:
      - "8003:80"
    depends_on:
      - db_secure_coding

  db_secure_coding:
    image: mysql:8.0
    container_name: mysql_db_secure_coding
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secure_coding
    volumes:
      - db_data_secure_coding:/var/lib/mysql
      - ./secure_coding.sql:/docker-entrypoint-initdb.d/database.sql:ro

volumes:
  db_data_secure_coding:
